// backend/services/orchestrator.js
const contextBuilder = require('../engine/context');
const firebaseService = require('./firebase');
const bigQueryService = require('./bigquery');
const decisionEngine = require('../engine/decision');
const vertexAIService = require('./vertex-ai');

class Orchestrator {
    constructor() {
        console.log('[Orchestrator] Service initialized with Google Cloud Integration.');
    }

    /**
     * Main agent flow: User Input -> BigQuery -> Vertex AI -> Firebase -> Output
     */
    async processUserQuery(userId, query) {
        console.log(`[Orchestrator] Processing query for User: ${userId} -> "${query}"`);
        
        try {
            // 1. Context Builder: Retrieve session state & history
            const session = contextBuilder.getSession(userId);
            contextBuilder.addHistory(userId, { role: 'user', content: query });

            // 2. Initial Data Gathering: Real-time from Firebase (Simulation helper)
            const crowdData = await firebaseService.getRealtimeCrowdData();

            // 3. Intent Pre-classification for Data Fetching logic
            let baseIntent = 'wayfinding';
            if (query.match(/emergency|fire|help/i)) baseIntent = 'emergency';
            else if (query.match(/food|eat|hungry/i)) baseIntent = 'food';
            else if (query.match(/park|car/i)) baseIntent = 'parking';
            else if (query.match(/exit|leave/i)) baseIntent = 'exit';

            // 4. BIGQUERY DATA FETCH (MANDATORY)
            // Fetch historical patterns to improve decision making
            let bqData = null;
            try {
                bqData = await bigQueryService.getHistoricalPattern(
                    baseIntent === 'exit' ? 'Gates' : 'Stadium',
                    baseIntent === 'food' ? 'halftime' : 'normal'
                );
            } catch (err) {
                console.error('[Orchestrator] BigQuery Fetch Error, continuing with engine defaults.');
            }

            // 5. Decision Engine logic (Rule-based pre-processing)
            const decisionData = decisionEngine.decideRoute(baseIntent, crowdData, session, bqData);

            // 6. VERTEX AI PROCESSING (MANDATORY)
            // Active usage of SDK: Analysis, classification, and reasoning
            const agentOutcome = await vertexAIService.classifyIntentAndReason(query, session, decisionData);
            
            // 7. FIREBASE LOGGING (MANDATORY/RECOMMENDED)
            // Active usage of SDK: Persisting interaction traces
            await firebaseService.logAgentOutcome(userId, {
                query,
                intent: agentOutcome.intent,
                structuredResponse: agentOutcome.structuredResponse
            });

            console.log(`[Orchestrator] Final Response generated by Vertex AI. Outcome logged to Firebase.`);
            
            // Update history with agent response
            contextBuilder.addHistory(userId, { role: 'assistant', content: agentOutcome.structuredResponse.message });

            return agentOutcome;

        } catch (err) {
            console.error(`[Orchestrator|CORE ERROR]`, err);
            return {
                intent: 'unknown',
                priority: 'normal',
                structuredResponse: {
                    destination: 'Center Field Help Desk',
                    direction: 'Central Paths',
                    crowdLevel: 0,
                    justification: 'System fall back due to error.',
                    message: `I'm having trouble accessing my backend services. Please head safely to the Center Field Help Desk.`
                }
            };
        }
    }
}

module.exports = new Orchestrator();
